name: Build Debian Package

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build package
        run: |
          dpkg-deb --build . proton-autogen.deb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: proton-autogen
          path: proton-autogen.deb
